l10n/messages.pot
src/components/Dialog.vue

After failing to authenticate the first time, hide the error while the new confirmation request is pending

Hide error message when reconfirming password and update message

---

README.md

Fix link to package on npm and replace deprecated Travis CI badge with the GitHub build workflow badge

Fix and update README badges

---

CHANGELOG.md
l10n/messages.pot
package-lock.json
package.json
src/components/Dialog.vue
src/globals.ts
src/main.ts

Fix dialog not appearing from the infinite focus trap loop due to the dialog and modal being mounted as siblings instead of being nested as described in https://github.com/tailwindlabs/headlessui/issues/825#issuecomment-927182208
The solution is to mount the dialog within the existing modal
Prepending to the previous modal is not enough as NcModal automatically remounts itself to `document.body` by default https://github.com/nextcloud/nextcloud-vue/blob/v7.0.0-beta.2/src/components/NcModal/NcModal.vue#L555-L561
So to prevent automatic mounting in NcModal `null` is passed to the `container` prop
This will show errors in the console that can be dismissed as it has no effect other than preventing automatic remounting but is addressed in https://github.com/nextcloud/nextcloud-vue/pull/3219

Fix dialog not appearing when another modal is open

---

CHANGELOG.md
README.md
package.json

Fix errors in https://github.com/nextcloud/server/pull/34044
The eslint errors `import/no-unresolved` and `node/no-missing-import` are due to the lack of support for the [`exports`](https://nodejs.org/api/packages.html#package-entry-points) field, see https://github.com/import-js/eslint-plugin-import/issues/1810 and https://github.com/mysticatea/eslint-plugin-node/issues/255
Switching from
```js
import '@nextcloud/password-confirmation/style.css'
```
to
```js
import '@nextcloud/password-confirmation/dist/style.css'
```
fixes the eslint errors but results in new build errors coming from `babel-loader`
```
Module not found: Error: Package path ./dist/style.css is not exported from package <path>/node_modules/@nextcloud/password-confirmation (see exports field in …
```

Remove exports field to fix eslint and build errors

---

l10n/messages.pot
package-lock.json
package.json
src/components/Dialog.vue

Fix https://github.com/nextcloud/server/issues/34217
Simpler in the end to just not use the built-in password policy checks from `NcPasswordField`
Addendum to https://github.com/nextcloud/nextcloud-password-confirmation/pull/399

Remove password policy checks completely to fix permanently disabled confirm button

---

package-lock.json
package.json
vite.config.ts

✓ 282 modules transformed.
dist/style.css   0.21 KiB / gzip: 0.15 KiB
dist/main.js     717.44 KiB / gzip: 203.73 KiB
dist/main.js.map 1937.99 KiB
✓ 15 modules transformed.
dist/style.css   0.21 KiB / gzip: 0.15 KiB
dist/main.js     37.21 KiB / gzip: 7.25 KiB
dist/main.js.map 136.01 KiB
For https://github.com/nextcloud/server/issues/36384

chore: Make dependencies external

---

src/utils/l10n.ts
tsconfig.json

`moduleResolution: node` is for `node v10` .. `node v15` (while engine is `node v20`) and doesn't support `package.json` fields `imports` and `exports`
https://www.typescriptlang.org/tsconfig#moduleResolution
`@nextcloud/l10n/dist/gettext.js` is not the correct import according to its `exports`: https://github.com/nextcloud-libraries/nextcloud-l10n/blob/609525946917bb3613773415966e2536484e66fe/package.json#L7-L18
It results in an incorrect bundle where `import { getGettextBuilder } from '@nextcloud/l10n/dist/gettext.js'` doesn't work on build
Try to update to `@nextcloud/vue@8` which uses `@nextcloud/l10n@2`, and build the server.
For example, here: https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/605

Fix `@nextcloud/l10n/gettext` import

---

README.md
src/main.ts

Though `confirmPassword` checks if password confirmation is required, IMO, for easier migration from deprecated `OC.PasswordConfirmation`, `isPasswordConfirmationRequired` should also be exported to replace public `OC.PasswordConfirmation.requiresPasswordConfirmation()`.

feat: export isPasswordConfirmationRequired

---

l10n/messages.pot
src/components/PasswordDialog.vue

**Blocked by https://github.com/nextcloud-libraries/nextcloud-password-confirmation/compare/update-nc-vue-to-v.8?expand=1**
Fixes https://github.com/nextcloud/server/pull/40643#issuecomment-1737733983
Fixes https://github.com/nextcloud/server/issues/37080#issuecomment-1736932044

Improve password confirmation dialog

---

README.md
src/main.ts

Manual backport of https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/609

[stable4] feat: export isPasswordConfirmationRequired

---

CHANGELOG.md
README.md
package-lock.json
package.json

⚠️ Waiting for backports:
1. https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/616
2. https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/617
- `isPasswordConfirmationRequired(): boolean` function to replace deprecated `OC.PasswordConfirmation.requiresPasswordConfirmation()`
- Fix compatibility with `@nextcloud/l10n@^2`
- Add `package.json/exports`
- Move to `nextcloud-libraries` organization
- Add ESLint for linting files
- Dependency updates

release: v4.1.0

---

CHANGELOG.md
README.md
package-lock.json
package.json

- Improve password confirmation dialog design and accessibility
- Major update `@nextcloud/vue` to v8.0.0-beta.7

Release v5.0.0

---

package.json
vite.config.mts

`npm run build` works because it has a bash script in `npm` script to rename the CSS chunk: `&& mv dist/main.css dist/style.css`
But `npm run dev` and `npm run watch` make an invalid bundle without this `move`.
This PR removes this move on npm script and changes the CSS chunk name in Vite config.
To test try to build server with dev build of this lib.

build: fix dev and watch build by specifying CSS chunk path

---

package-lock.json
package.json

The `-beta` suffix will not allow to use the stable version.
Moreover we should generally now require the stable version :wink:

fix: Adjust peer dependency on `@nextcloud/vue` to allow stable version

---

src/env.d.ts
src/utils/l10n.ts
vite.config.ts

This reduces the bundle size from ~36KiB to ~17KiB. This parts can not be treeshaken so this will fully affect apps, meaning each app will shrink by ~19KiB.

enh: Compress translations to reduce bundle size

---

l10n/messages.pot
package-lock.json
package.json
src/components/PasswordDialog.vue
src/vite-env.d.ts
src/vue-shims.d.ts
tsconfig.json

* This requires #693 first!
Use NcDialog instead of NcModal, so we can reduce the boilerplate code (styles etc).
*sorry forgot to switch to English language*
before | after
---|---

enh: Migrate to NcDialog

---

package.json

Export the types instead of the faulty export the styles as the types :eyes:

fix: Correctly export Typescript types in `exports`

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-password-confirmation/compare/v5.1.0...v5.1.1)
* fix: Correctly export Typescript types in `exports` [\#795](https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/795)
* Updated translations
* chore(deps): Bump @nextcloud/router to 3.0.1
* chore(deps): Bump @nextcloud/axios to 2.5.0
* chore(deps): Bump @nextcloud/l10n to 3.1.0
* chore(dev-deps): Update development dependencies [\#794](https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/794)
* chore: Update workflows from organization [\#797](https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/797)

chore: Prepare release of 5.1.1

---

package-lock.json
package.json
src/components/PasswordDialog.vue
src/globals.ts
src/main.ts

This eases requesting for password confirmation

feat: Expose axios interceptors

---

CHANGELOG.md
package-lock.json
package.json

* feat: Expose axios interceptors by @artonge in https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/881
* chore(deps): Bump skjnldsv/read-package-engines-version-actions to 3
* chore(deps): Bump actions/setup-node to 4.1.0
* chore(deps): Bump axios to 1.7.4
* chore(deps): Bump @nextcloud/axios to 2.5.1
* chore(deps): Bump pascalgn/automerge-action to 0.16.4
* chore(deps): Bump rollup to 4.22.4
* chore(deps): Bump actions/checkout to 4.2.2
* chore(deps): Bump dompurify to 3.1.7
* chore(deps-dev): Bump @types/node to 20.14.12
* chore(deps-dev): Bump vite to 5.4.11
* chore(deps-dev): Bump typescript to 5.7.2
* chore(deps-dev): Bump sass to 1.81.0
* chore(deps-dev): Bump @nextcloud/vite-config to 1.4.2
* chore(deps-dev): Bump elliptic to 6.6.0
* chore: Add SPDX …

chore: Prepare: v5.2.0

---

README.md
src/globals.ts

- Follow-up of https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/881

chore: Document axios interceptor and PwdConfirmationMode

---

package-lock.json
package.json
src/components/PasswordDialog.vue
src/main.ts

I tested this with twofactor_webauthn and it works fine.
This is a breaking change and we need to maintain two versions for the foreseeable future. One for Vue 2 and one for Vue 3.

feat!: migrate to vue 3

---

.github/dependabot.yml
CHANGELOG.md
README.md
package-lock.json
package.json

* similar to how it is done on nextcloud-dialogs
* closes https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/915
This allows in theory (tested) to also use this library with Vue 2 apps. For those the bundle size will increase as Vue needs to bundled two times, but if you use Vue 3 all works as intended (only bundled once so small asset size).
This allows us to drop maintenance on v5 as soon as Nextcloud 31 gets EOL.

chore: move vue dependencies to plain dependencies

---

CHANGELOG.md
package.json

simplify the entry points by only allow one way of importing the styles.

chore!: drop legacy style entry point

---

eslint.config.js
package-lock.json
package.json
src/components/PasswordDialog.vue
src/password-confirmation.ts
src/utils/logger.spec.ts
src/utils/logger.ts

If the admin configured the frontend to not display debug messages we should respect that. So instead of console we should use the logger for all messages.

chore: migrate to nextcloud-logger to respect logging level

---

REUSE.toml
build/typedoc-shims.d.ts
src/vue-shims.d.ts
tsconfig.typedoc.json
typedoc.json

All vue modules used are declared already, so we only need to mock it for NcPasswordField as this is not yet migrated to Typescript.

chore: drop unneeded TS declarations
